<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Contorion\SearchShelter\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Petstore
 *
 * This is a sample Shelter server [http://swagger.io](http://swagger.io) or on  [irc.freenode.net, #swagger](http://swagger.io/irc/).
 *
 * OpenAPI spec version: 1.0.1
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Contorion\SearchShelter\SwaggerClient;

use \Contorion\SearchShelter\SwaggerClient\Configuration;
use \Contorion\SearchShelter\SwaggerClient\ApiException;
use \Contorion\SearchShelter\SwaggerClient\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Contorion\SearchShelter\SwaggerClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addAnimal
     *
     * Add a new animal to shelter.
     *
     */
    public function testAddAnimal()
    {
    }

    /**
     * Test case for addShelter
     *
     * Add a new shelter.
     *
     */
    public function testAddShelter()
    {
    }

    /**
     * Test case for addWorker
     *
     * Add a new worker to shelter.
     *
     */
    public function testAddWorker()
    {
    }

    /**
     * Test case for deleteAnimal
     *
     * Delete animal from the system.
     *
     */
    public function testDeleteAnimal()
    {
    }

    /**
     * Test case for deleteShelter
     *
     * Delete shelter from the system.
     *
     */
    public function testDeleteShelter()
    {
    }

    /**
     * Test case for deleteWorker
     *
     * Delete worker from the system.
     *
     */
    public function testDeleteWorker()
    {
    }

    /**
     * Test case for listShelterAnimals
     *
     * List worker of a shelter.
     *
     */
    public function testListShelterAnimals()
    {
    }

    /**
     * Test case for listShelterWorkers
     *
     * List worker of a shelter.
     *
     */
    public function testListShelterWorkers()
    {
    }
}
